name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install mise
      uses: jdx/mise-action@v2
      with:
        version: 2025.10.18

    - name: Install dependencies
      run: mise run install

    - name: Run linter
      run: mise run lint

    - name: Run type checker
      run: mise run type-check

    - name: Run tests
      run: mise run test

    - name: Run tests with coverage
      run: mise run test-cov
