name: CI (Simple)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run linter
      run: |
        black --check src tests
        ruff check src tests

    - name: Run type checker
      run: mypy src

    - name: Run tests
      run: pytest tests -vv

    - name: Run tests with coverage
      run: pytest tests -vv --cov=src --cov-report=term-missing
